<?php declare(strict_types=1);

/**
 * Encrypted Web Token (EWT) Interface
 *
 * Defines the contract for EWT operations including encoding and decoding
 * of encrypted web tokens. Provides a clean interface for working with
 * encrypted tokens in the Spin framework.
 *
 * @package  Spin\Helpers
 * @author   Spin Framework Team
 * @since    1.0.0
 */

namespace Spin\Helpers;

interface EWTInterface
{
  /**
   * Encode $data with params and return a Base64 string representing the EWT
   *
   * @param   string $data            The plain-text payload to encrypt
   * @param   string $secret          The secret password to use
   * @param   string $hash            The HMAC algorithm. 'sha256' by default
   * @param   string $alg             The OpenSSL Cipher algorithm. AES-256-ctr by default
   * @param   string|null $iv         The Initialization Vector to use. Autogenerated by default
   *
   * @return  string                  The resulting EWT
   */
  static function encode($data, string $secret, string $hash='sha256', string $alg='aes-256-ctr', ?string $iv=null );

  /**
   * Decode an EWT, returning the payload
   *
   * @param      string  $data    The encrypted EWT base64 string
   * @param      string  $secret  Secret password used when encrypting
   *
   * @return     string|null
   */
  static function decode(string $data, string $secret );

}
