<?php declare(strict_types=1);

/**
 * EWTInterface
 * 
 * Encrypted Web Token Interface
 *
 * @package  Spin
 */

namespace Spin\Helpers;

interface EWTInterface
{
    /**
     * Encode $data with params and return a Base64 string representing the EWT
     *
     * @param      string       $data    The plain-text payload to encryot
     * @param      string       $secret  The secret password to use
     * @param      string       $hash    The hash algorithm. SHA256 by default
     * @param      string       $alg     The OpenSSL Cipher algorithm.
     *                                   AES-256-CTR by default
     * @param      string|null  $iv      The Initialization Vector to use.
     *                                   Autogenerated by default
     *
     * @return     string  The resulting EWT
     */
  static function encode($data, string $secret, string $hash='sha256', string $alg='aes-256-ctr', string $iv=null );

  /**
   * Decode an EWT, returning the payload
   *
   * @param      string  $data    The encrypted EWT base64 string
   * @param      string  $secret  Secret password used when encrypting
   *
   * @return     string|null
   */
  static function decode(string $data, string $secret );

}
